### ISSUE TITLE
demo.jl script looks for non-existing "images/demo.pfm"  file

### ISSUE THREAD

**Issue by lorycontixd** [DanieleZambetti97/ProjectMoana#8]
The package is trying to use a file that does not exist. Hope you fix this.

**Comment by GiacomoRivolta** [comment]
Fixed! Release 0.2.1 is now correct. Thank you @lorycontixd ! 😄 ❤️

**Comment by lorycontixd** [comment]
Thank you bro @GiacomoRivolta
