### ISSUE TITLE
Indexing problem

### ISSUE THREAD

**Issue by GiacomoRivolta** [DanieleZambetti97/ProjectMoana#9]
The function fire_ray in Cameras.jl is firing rays to the wrong pixels: their indexes are shifted of a factor (1, 1). Thus the pixel-grid generated by a generic Camera is not aligned with the objects of the World.

**Comment by DanieleZambetti97** [comment]
Fixed with this [commit](https://github.com/DanieleZambetti97/ProjectMoana/commit/abe6e08af9a7d2204b7599291fb64e0e784fae1fl).
